<center><h1> Corréction Série de Travaux Pratiques N° 6 - Machine Learning </h1></center>
<center><h2> Regression Logistique</h2></center>

---



# **Partie I : Regression Logistique**

Vous trouverez ci-joint un exemple d'utilisation d'algorithme de regréssion logistique avec les quatres étapes principales.

In [1]:
# Step 1: Import packages, functions
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

# Step 2: Get data
x = np.arange(10).reshape(-1, 1)
y = np.array([0, 1, 0, 0, 1, 1, 1, 1, 1, 1])

# Step 3: Create a model and train it
model = LogisticRegression(solver='liblinear', C=10.0, random_state=0, max_iter=100)
model.fit(x, y)

# Step 4: Evaluate the model
p_pred = model.predict_proba(x)
y_pred = model.predict(x)
score_ = model.score(x, y)
conf_m = confusion_matrix(y, y_pred)
report = classification_report(y, y_pred)

In [2]:
print('x:', x)
print('y:', y)
print('intercept:', model.intercept_)
print('coef:', model.coef_)
print('p_pred:', p_pred)
print('y_pred:', y_pred)
print('score_:', score_)
print('conf_m:', conf_m)
print('report:', report)

x: [[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
y: [0 1 0 0 1 1 1 1 1 1]
intercept: [-1.51632619]
coef: [[0.703457]]
p_pred: [[0.81999686 0.18000314]
 [0.69272057 0.30727943]
 [0.52732579 0.47267421]
 [0.35570732 0.64429268]
 [0.21458576 0.78541424]
 [0.11910229 0.88089771]
 [0.06271329 0.93728671]
 [0.03205032 0.96794968]
 [0.0161218  0.9838782 ]
 [0.00804372 0.99195628]]
y_pred: [0 0 0 1 1 1 1 1 1 1]
score_: 0.8
conf_m: [[2 1]
 [1 6]]
report:               precision    recall  f1-score   support

           0       0.67      0.67      0.67         3
           1       0.86      0.86      0.86         7

    accuracy                           0.80        10
   macro avg       0.76      0.76      0.76        10
weighted avg       0.80      0.80      0.80        10



# **Partie II : Classification Binaire**

L'objectif de l'ensemble de données "**diabetes.csv**" est de prédire, sur la base de mesures diagnostiques, si un patient **souffre de diabète ou pas**.

Ce dataset contient les caractéristiques suivants

**Grossesses**: Nombre de fois enceintes.

**Glucose**: concentration plasmatique de glucose à 2 heures lors d'un test oral de tolérance au glucose.

**Pression artérielle** : tension artérielle diastolique (mm Hg).

**Épaisseur de la peau** : épaisseur du pli cutané du triceps (mm).

**Insuline** : insuline sérique de 2 heures (mu U/ml).

**IMC** : Indice de masse corporelle (poids en kg/(taille en m)^2).

**DiabetesPedigreeFunction** : fonction généalogique du diabète.

**Âge** : Âge (ans).

**Résultat** : variable de classe (0 ou 1).

### **Questions :**

Étape 1 : Importer et afficher et explorer l'ensemble de données "**diabetes.csv**"

Étape 2 : Créer dépendante d'une variable indépendante et stockée sur les variables X et Y.

Étape 3 : Transformer les chaînes en entier.

Étape 4 : Divisez les données en ensembles d'entrainement et de test.

Étape 5 : Définir l'algorithme de régression logistique.

Étape 6 :Tester les données de test en utilisant votre modèle.

Étape 7 : Évaluation du modèle.

Étape 8 : Prédire avec de nouvelles valeurs.

In [54]:
# # Se connecter
#from google.colab import drive
#drive.mount('/content/drive')
#Étape 1 : 
import numpy as np
from sklearn.metrics import classification_report, confusion_matrix
import pandas as pd

data= pd.read_csv('diabetes.csv')
data.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [58]:
#Étape 2 : 
X = data.iloc[:,:8]
Y = data.iloc[:,-1]
Y.head()

0    1
1    0
2    1
3    0
4    1
Name: Outcome, dtype: int64

In [13]:
#Étape 4: 
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
Y = LabelEncoder().fit_transform(Y)
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.33, random_state=42)
print(X_train, X_test, Y_train, Y_test)

     Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
464           10      115             98              0        0  24.0   
223            7      142             60             33      190  28.8   
393            4      116             72             12       87  22.1   
766            1      126             60              0        0  30.1   
570            3       78             70              0        0  32.5   
..           ...      ...            ...            ...      ...   ...   
71             5      139             64             35      140  28.6   
106            1       96            122              0        0  22.4   
270           10      101             86             37        0  45.6   
435            0      141              0              0        0  42.4   
102            0      125             96              0        0  22.5   

     DiabetesPedigreeFunction  Age  
464                     1.022   34  
223                     0.687   61  


In [28]:
#Étape 5:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(solver='liblinear', C=10.0, random_state=0, max_iter=100)

In [29]:
#Étape 6:
model.fit(X_train, Y_train)

LogisticRegression(C=10.0, random_state=0, solver='liblinear')

In [32]:
#Étape 7:

Y_pred = model.predict(X_test)

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

accuracy = accuracy_score(Y_test, Y_pred)
precision = precision_score(Y_test, Y_pred)
recall = recall_score(Y_test, Y_pred)
f1 = f1_score(Y_test, Y_pred)
conf_matrix = confusion_matrix(Y_test, Y_pred)

print("Précision :", accuracy)
print("Précision :", precision)
print("Rappel :", recall)
print("F1-score :", f1)
print('Confusion Matrix:')
print(conf_matrix)

Précision : 0.7519685039370079
Précision : 0.6385542168674698
Rappel : 0.6162790697674418
F1-score : 0.6272189349112426
Confusion Matrix:
[[138  30]
 [ 33  53]]


In [33]:
#Étape 8:
new_data = np.array([[2, 85, 66, 23, 40, 26.6, 0.35, 31]])  
new_prediction = model.predict(new_data)

if new_prediction == 0:
    print("Le patient est à faible risque de diabète.")
else:
    print("Le patient est à haut risque de diabète.")

Prediction for new data: [0]


C:\Users\Lenovo\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


# **Partie II : Classification Multi-Classe**

Pour cette partie, on utilisera le **dataset IRIS**. Ce dernier est une base de données regroupant les caractéristiques de **trois espèces de fleurs d’Iris, à savoir Setosa, Versicolour et Virginica**. Chaque ligne de ce jeu de données est une observation des caractéristiques d’une fleur d’Iris. Ce dataset décrit les espèces d’Iris par quatre propriétés : longueur et largeur de sépales ainsi que longueur et largeur de pétales. La base de données comporte 150 observations (50 observations par espèce).

### **Questions :**

Étape 1 : Importer, afficher et explorer l'ensemble de données "**iris.csv**"

Étape 2 : Créer dépendante d'une variable indépendante et stockée sur les variables X et Y.

Étape 3 : Transformer les chaînes en entier.

Étape 4 : Divisez les données en ensembles d'entrainement et de test.

Étape 5 : Définir l'algorithme de régression logistique.

Étape 6 :Tester les données de test en utilisant votre modèle.

Étape 7 : Évaluation du modèle.

Étape 8 : Prédire avec de nouvelles valeurs.

In [34]:
# Multi-Class Classification : IRIS Dataset
#Étape 1 : 
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
import pandas as pd

data= pd.read_csv('iris.csv')
data.head()



sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [35]:
#Étape 2 :
X = data.iloc[:,:4]
Y = data.iloc[:,-1]
Y.head()

0    Setosa
1    Setosa
2    Setosa
3    Setosa
4    Setosa
Name: variety, dtype: object

In [36]:
#Étape 3 :
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
Y = label_encoder.fit_transform(Y)

print(Y[:53]) 

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1]


In [37]:
#Étape 4 :
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
Y = LabelEncoder().fit_transform(Y)
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)
print(X_train, X_test, Y_train, Y_test)


     sepal.length  sepal.width  petal.length  petal.width
22            4.6          3.6           1.0          0.2
15            5.7          4.4           1.5          0.4
65            6.7          3.1           4.4          1.4
11            4.8          3.4           1.6          0.2
42            4.4          3.2           1.3          0.2
..            ...          ...           ...          ...
71            6.1          2.8           4.0          1.3
106           4.9          2.5           4.5          1.7
14            5.8          4.0           1.2          0.2
92            5.8          2.6           4.0          1.2
102           7.1          3.0           5.9          2.1

[120 rows x 4 columns]      sepal.length  sepal.width  petal.length  petal.width
73            6.1          2.8           4.7          1.2
18            5.7          3.8           1.7          0.3
118           7.7          2.6           6.9          2.3
78            6.0          2.9           4.5    

In [43]:
#Étape 5 :
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(solver='liblinear', C=10.0, random_state=0, max_iter=200)
model.fit(X_train, Y_train)

LogisticRegression(C=10.0, max_iter=200, random_state=0, solver='liblinear')

In [44]:
#Étape 6:
Y_pred = model.predict(X_test)

print(Y_pred[:5]) 


[1 0 2 1 1]


In [50]:
#Étape 7:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Évaluer la précision du modèle
accuracy = accuracy_score(Y_test, Y_pred)
print(f'Accuracy: {accuracy:.2f}')

# Afficher le rapport de classification
print(classification_report(Y_test, Y_pred))

# Afficher la matrice de confusion
print(confusion_matrix(Y_test, Y_pred))


Accuracy: 1.00
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


In [51]:
#Étape 8:
# Définir de nouvelles valeurs pour prédiction
new_values = [[5.1, 3.5, 1.4, 0.2],  # Iris Setosa
              [6.0, 2.9, 4.5, 1.5],  # Iris Versicolour
              [6.3, 3.3, 6.0, 2.5]]  # Iris Virginica

# Prédire les espèces pour les nouvelles valeurs
new_predictions = model.predict(new_values)
new_predictions_species = label_encoder.inverse_transform(new_predictions)

print(new_predictions_species)

['Setosa' 'Versicolor' 'Virginica']


C:\Users\Lenovo\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
